# Generated by Django 3.2.3 on 2023-10-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='achievementcat',
            options={'verbose_name': 'Достижение кота', 'verbose_name_plural': 'Достижения котов'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
    ]
